application: rfrlus
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest

handlers:
- url: /js
  static_dir: js/

- url: /css
  static_dir: css/

- url: /.*
  script: rfrlus.application

